Dev/guma/refactor vector3
GSharker/G-Shark pull request #137
Opened 2021-06-11 05:28 UTC by d3ssy

- Added Vector3d (to replace Vector3)
- Added Point3d (to replace Vector3 where appropriate)
- Added Point4d (to be represent a Control Point)

2021-06-11 06:35 UTC, sonomirco requested changes
Something that we can do at the end but I still prefer Vector3, Point3 as the name of the classes.
I don't see ControlPoint.

2021-06-11 06:35 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/Point3dTests.cs
> +
Space

2021-06-11 06:35 UTC, sonomirco commented on src/GShark/Core/Transform.cs
>      public class Transform : List<IList<double>>
Do we still need to inherit from a List, now that we have parameters?

2021-06-11 06:35 UTC, sonomirco commented on src/GShark/Geometry/Point3d.cs
> -        public static Point3d[] CullDuplicates(System.Collections.Generic.IEnumerable<Point3d> points, double tolerance)
This method shouldn't be somewhere into operation? Maybe Analyze?

2021-06-11 06:35 UTC, sonomirco commented on src/GShark/Geometry/Point3d.cs
> +        public double MinimumCoordinate
I don't think we need this one.

2021-06-11 06:35 UTC, sonomirco commented on src/GShark/Geometry/Point3d.cs
> +        public double MaximumCoordinate
Same for this one

2021-06-11 06:35 UTC, sonomirco commented on src/GShark/Geometry/Vector3d.cs
> +            /// Computes the perpendicular to another vector.<br/>
Indentation here

2021-06-11 06:40 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/Vector3dTests.cs
> +        public void It_Checks_If_Two_Vectors_Are_Parallel(/*double[] v4, double[] v2, int result*/)
Do we need the comments into the parenthesis?

2021-06-11 06:46 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/Vector3dTests.cs
> +        public void Unitize_Throws_An_Error_If_Vector_Or_Zero_Length()
Is this test correct? It checks if unitize throws an error but the assert checks if it is true.

2021-06-12 04:44 UTC, d3ssy commented on src/GShark/Core/Transform.cs
>      public class Transform : List<IList<double>>
I think it would still be nice for it to be indexable, but can implement that with an indexer instead of inheriting from List. It depends where in the codebase it is currently being used as a List. Didn't want to create too many changes at once! ;)

2021-06-12 05:03 UTC, d3ssy commented on src/GShark/Geometry/Point3d.cs
> -        public static Point3d[] CullDuplicates(System.Collections.Generic.IEnumerable<Point3d> points, double tolerance)
Didn't see a good place for it in Operation. Definitely not an analysis (in that case it would be the opposite, something like FindDuplicates). Considered having it as extension on Point3d, but then it may as well remain in the class! Considered Utilities as well, but I saw those more as internal helpers.

2021-06-14 00:33 UTC, sonomirco commented on src/GShark/Geometry/Point3d.cs
> -        public static Point3d[] CullDuplicates(System.Collections.Generic.IEnumerable<Point3d> points, double tolerance)
ok as internal helper :)

2021-06-14 00:34 UTC, merged