LoftedSurface finished
GSharker/G-Shark pull request #224
Opened 2021-08-01 15:27 UTC by pedrocortesark

Develop solution for lofted surface creation method and its unit test

### What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [X ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

### Description

Finished task #116 CreateLoftedSurface. Unit test has been also created and tested

This PR adds this: LoftedSurface. 

### Related Tickets & Documents

### Added tests?

- [ X] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📓 docs
- [X ] 🙅 no documentation needed

2021-08-01 20:50 UTC, cesarecaoduro approved these changes

2021-08-01 22:57 UTC, sonomirco requested changes

2021-08-01 22:57 UTC, sonomirco commented on src/GShark/Geometry/NurbsSurface.cs
> +        public static NurbsSurface CreateLoftedSurface(List<NurbsCurve> crvs, int degreeU)
Should it be degreeV?
You can set it as per default = 3, ``int degreeU = 3``, this we can avoid checking if this parameter is null later.

2021-08-01 22:57 UTC, sonomirco commented on src/GShark/Geometry/NurbsSurface.cs
> +            int degreeV = crvs[0].Degree;
We should do some checking on the list of curves.
1. checks if the list of curves is empty, throw an error.
2. checks if all the curves are open or close, if are mixed throw an error, with a message like _"Loft only works if all curves are open, or all curves are closed."_
3. clean the list, if there is a curve not valid, removed it from the list.

These checks have to be captured into the tests.

2021-08-01 22:57 UTC, sonomirco commented on src/GShark/Geometry/NurbsSurface.cs
> +            int degreeV = crvs[0].Degree;
missed this check
``if (degreeV > curves.length - 1){
            degreeV = curves.length - 1;
        }``

2021-08-01 22:57 UTC, sonomirco commented on src/GShark/Geometry/NurbsSurface.cs
> +            KnotVector knotU = new KnotVector(degreeU, crvs.Count);
this can be taken by the curve ``var knotsU = curves[0].knots;``

2021-08-01 22:57 UTC, sonomirco commented on src/GShark/Geometry/NurbsSurface.cs
> +            List<List<Point3>> points = crvs.Select(x => x.LocationPoints).ToList();
Why did you remove all the interpolation steps?
https://github.com/pboyer/verb/blob/3692d7c5f41aab43eef457e74fc0e0513b252cbd/src/verb/eval/Make.hx#L147

2021-08-01 22:57 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
> +            surface.Should().NotBeNull();
To validate the surface probably is good to check some points at the UV values and see if the surface is correct.

2021-08-01 22:57 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
> +        public void It_Returns_A_NURBS_Lofted_Surface()
To mock up the tests, I normally use grasshopper.
There is a GH definition in the Tests proj called GHDebugSurface, where you can simulate them.
Example
![image](https://user-images.githubusercontent.com/57708659/127787760-c88c671b-e402-4e10-a80b-d56518721417.png)

2021-08-02 11:56 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +        public static NurbsSurface CreateLoftedSurface(List<NurbsCurve> crvs, int degreeU)
As an answer to the question, yes, I think it should be degreeU according to the data in points list of lists... And it's true, with the default parameter we avoid the null ckeck!

2021-08-02 15:48 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +        public static NurbsSurface CreateLoftedSurface(List<NurbsCurve> crvs, int degreeU)
Yeah... I've been checking the verb example and I refactor my code to make it more similar to the reference...

2021-08-02 15:48 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +            int degreeV = crvs[0].Degree;
Done!

2021-08-02 15:49 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +            KnotVector knotU = new KnotVector(degreeU, crvs.Count);
Done!

2021-08-02 15:49 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +            List<List<Point3>> points = crvs.Select(x => x.LocationPoints).ToList();
Done!

2021-08-02 15:53 UTC, pedrocortesark commented on src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
> +        public void It_Returns_A_NURBS_Lofted_Surface()
Done!

2021-08-02 15:54 UTC, pedrocortesark commented on src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
> +            surface.Should().NotBeNull();
Done!

2021-08-03 07:21 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +            int degreeV = crvs[0].Degree;
Done!

2021-08-03 09:08 UTC, sonomirco requested changes
Add the muck-up tests you have in the GHDebugLoftSurface into GHDebugSurface, we keep only one file.

2021-08-03 09:08 UTC, sonomirco commented on src/GShark/Geometry/NurbsSurface.cs
> +        public static NurbsSurface CreateLoftedSurface(List<NurbsCurve> crvsInput, int degreeV = 3)
We should think to add an enumerator called LoftType where for now we will have Normal and Loose.
When is Loose you keep the pts as they are, when is normal you use ``InterpolatedCurve``

Feel free to investigate more on the other loof types are in Rhino to see what we can replicate/add.

2021-08-03 15:11 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +                throw new ArgumentException("Invalid initial curves! You should select at least 2 curves");
Done!

2021-08-03 15:14 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +
Done!

2021-08-04 05:00 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +                List<Point3> pts = crvs.Select(c => c.LocationPoints[n]).ToList();
Done!

2021-08-04 05:38 UTC, pedrocortesark commented on src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
> +            Point3 evalPt1 = Evaluation.SurfacePointAt(surface, 0.5, 0.5);
Perfect

2021-08-04 06:14 UTC, pedrocortesark commented on src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
> +            Point3 expectedPt1 = new Point3(6.5625, 17.5, 6.75);
Done!

2021-08-04 14:30 UTC, pedrocortesark commented on src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
> +            surface.LocationPoints.Count.Should().Be(3);
Because the U direction is composed by the number of control points in the curves, in this case 3. The number of curves set the number of control points in V direction, 4.

2021-08-04 14:40 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +            HashSet<bool> set = new HashSet<bool>( crvs.Select( x => x.IsClosed() == true ).ToList() );
I create the set just to evaluate if every curves are opened or closed. If the set has two elements, it'll mean we have a combination of opened and closed curves and it'll throw the error

2021-08-04 21:03 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/NurbsSurfaceTests.cs
> +            surface.LocationPoints.Count.Should().Be(3);
Ok, but again is not a necessary test, rather than you are modifying the number of points.

2021-08-04 21:07 UTC, sonomirco commented on src/GShark/Geometry/NurbsSurface.cs
> +            HashSet<bool> set = new HashSet<bool>( crvs.Select( x => x.IsClosed() == true ).ToList() );
is not purpose of using any?
At the end you are checking if all the curve are open or close there is not a middle way.
So using any you have directly your answer.

2021-08-06 09:59 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
> +        [Theory]
Please remove these tests.

2021-08-06 10:05 UTC, pedrocortesark commented on src/GShark.Test.XUnit/Geometry/NurbsCurveTests.cs
> +        [Theory]
ok!

2021-08-06 10:06 UTC, sonomirco requested changes

2021-08-06 10:06 UTC, sonomirco commented on src/GShark/Geometry/Enum/LoftType.cs
> +        Tight,
You can remove this

2021-08-06 10:06 UTC, sonomirco commented on src/GShark/Geometry/Enum/LoftType.cs
> +        /// The sections between the curves are straight
Dot at the end.

2021-08-06 10:06 UTC, sonomirco commented on src/GShark/Geometry/Enum/LoftType.cs
> +        Straight,
This has to be developed.

2021-08-06 10:06 UTC, sonomirco commented on src/GShark/Geometry/Enum/LoftType.cs
> +        Uniform
This can be developed or removed.

2021-08-06 10:06 UTC, sonomirco commented on src/GShark/Geometry/NurbsSurface.cs
> +                        List<Point3> pts = crvs.Select(c => c.LocationPoints[n]).ToList();
these two lines are not necessary.
You have already the points, you are just moving the points from a list to another list.

2021-08-06 10:06 UTC, sonomirco commented on src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
> +        public static List<NurbsCurve> SetOfOpenedNurbsCurves()
Rename in OpenCurves

2021-08-06 10:08 UTC, pedrocortesark commented on src/GShark/Geometry/Enum/LoftType.cs
> +        /// The surface control points are created at the same locations as the control points of the loft input curves
Ok!

2021-08-06 10:09 UTC, sonomirco commented on src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
> +        public static List<NurbsCurve> SetOfClosedNurbsCurves()
Rename to ClosedCurves

2021-08-06 10:10 UTC, pedrocortesark commented on src/GShark/Geometry/Enum/LoftType.cs
> +        Tight,
ok!

2021-08-06 10:10 UTC, pedrocortesark commented on src/GShark/Geometry/Enum/LoftType.cs
> +        /// The sections between the curves are straight
ok!

2021-08-06 10:10 UTC, pedrocortesark commented on src/GShark/Geometry/Enum/LoftType.cs
> +        Straight,
ok!

2021-08-06 10:10 UTC, pedrocortesark commented on src/GShark/Geometry/Enum/LoftType.cs
> +        Uniform
ok!

2021-08-06 10:12 UTC, pedrocortesark commented on src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
> +        public static List<NurbsCurve> SetOfOpenedNurbsCurves()
ok!

2021-08-06 10:12 UTC, pedrocortesark commented on src/GShark.Test.XUnit/Data/NurbsCurveCollection.cs
> +        public static List<NurbsCurve> SetOfClosedNurbsCurves()
ok!

2021-08-07 01:42 UTC, d3ssy approved these changes

2021-08-07 01:42 UTC, d3ssy commented on src/GShark/Geometry/NurbsSurface.cs
> +                    throw new ArgumentException("Loft only works if all curves are open, or all curves are closed.");
Use `if(crvs.Any(crv => crv.IsPeriodic != crvs[0].IsPeriodic) throw...`

2021-08-07 01:42 UTC, d3ssy commented on src/GShark/Geometry/NurbsSurface.cs
> +
degreeV > crvs.Count -1 should throw exception. Should be second exception to avoid iterating over crvs if this is the case.

2021-08-07 01:42 UTC, d3ssy commented on src/GShark/Geometry/NurbsSurface.cs
> +            List<NurbsCurve> crvs = crvsInput.Where(x => x != null).ToList();
Do not remove nulls. Throw exception instead indicating input contains null curves.

2021-08-07 01:42 UTC, d3ssy commented on src/GShark/Geometry/NurbsSurface.cs
> +            KnotVector knotV = new KnotVector();
rename to knotVectorU, or knotsU

2021-08-07 01:42 UTC, d3ssy commented on src/GShark/Geometry/NurbsSurface.cs
> +            List<List<Point3>> ptsSurf = new List<List<Point3>>();
rename to surfaceControlPoints, srfPts, srfCtrlPts, controlPoints, ctrlPts, etc.

2021-08-07 01:42 UTC, d3ssy commented on src/GShark/Geometry/NurbsSurface.cs
> +        /// <param name="degreeV">Degree of surface in V direction.</param>
Communicate relationship to input curves count.

2021-08-07 01:42 UTC, d3ssy commented on src/GShark/Geometry/NurbsSurface.cs
> +        public static NurbsSurface CreateLoftedSurface(List<NurbsCurve> crvsInput, int degreeV = 3, LoftType loftType = LoftType.Normal)
rename crvsInput to curves. All method arguments are inputs.

2021-08-07 10:33 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +        public static NurbsSurface CreateLoftedSurface(List<NurbsCurve> crvsInput, int degreeV = 3, LoftType loftType = LoftType.Normal)
Done!

2021-08-07 10:36 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +        /// <param name="degreeV">Degree of surface in V direction.</param>
Done!

2021-08-07 10:39 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +            List<List<Point3>> ptsSurf = new List<List<Point3>>();
Done!

2021-08-07 10:39 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +            KnotVector knotV = new KnotVector();
Done!

2021-08-07 11:00 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +
Done!

2021-08-07 11:00 UTC, pedrocortesark commented on src/GShark/Geometry/NurbsSurface.cs
> +            List<NurbsCurve> crvs = crvsInput.Where(x => x != null).ToList();
Done! And test added!

2021-08-16 12:29 UTC, merged