Adds Mesh implementation
GSharker/G-Shark pull request #397
Opened 2023-01-05 08:21 UTC by AlanRynne

DRAFT:

2023-01-05 22:28 UTC, sonomirco commented
Hey @AlanRynne, could we start to review this PR?

2023-01-05 23:47 UTC, d3ssy commented
> Hey @AlanRynne, could we start to review this PR?

Reviewed with Alan this AM based on comments on previous PR. Fresh commits coming in soon and then ready to merge! 🚀

2023-01-06 08:35 UTC, d3ssy commented on src/GShark/Geometry/MeshGeometry.cs
> +                case 3: // Triangle face
@sonomirco this one.

2023-01-06 08:35 UTC, d3ssy requested changes
Changes as discussed in previous review.

2023-01-16 20:55 UTC, AlanRynne commented
Hi all! Sorry for the delay on this I've been a bit busy lately! I'm planning on wrapping this up between today and tomorrow and leave it up to you guys to review for any improvements! 👍🏻

2023-01-17 01:54 UTC, d3ssy commented
Noice. 🤘

On Mon, Jan 16, 2023, 2:55 PM Alan Rynne ***@***.***> wrote:

> Hi all! Sorry for the delay on this I've been a bit busy lately! I'm
> planning on wrapping this up between today and tomorrow and leave it up to
> you guys to review for any improvements! 👍🏻
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GSharker/G-Shark/pull/397#issuecomment-1384540467>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABPXUISKJTU56WRVROWYGI3WSWYUTANCNFSM6AAAAAATRVMNRY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-02-07 13:43 UTC, d3ssy commented
@AlanRynne is this good to go?!

2023-02-20 21:42 UTC, sonomirco commented
@AlanRynne, any updates on this branch?

2023-03-12 15:08 UTC, AlanRynne commented
Hey @sonomirco, @d3ssy! I would have sworn I had pinged you guys here to review this... but I seemed to have left my message unsent 🙇🏼‍♂️

I think this one is ready to go unless you have any particular opinions on any part of the code ;)

2023-05-03 23:01 UTC, merged