Area of a triangle
GSharker/G-Shark pull request #399
Opened 2023-01-05 23:53 UTC by sonomirco

### What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [x] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

### Description

This PR added the faction to calculate the area of a triangle.

### Related Tickets & Documents

This PR closes #398 

### Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [x] 📓 docs
- [ ] 🙅 no documentation needed

2023-01-06 01:14 UTC, cesarecaoduro commented on src/GShark/Core/Trigonometry.cs
> +            var pts = polyLine.ControlPointLocations;
Shouldn't we do some check on the number of vertices for the polyline?

2023-01-06 02:03 UTC, sonomirco commented on src/GShark/Core/Trigonometry.cs
> +            var pts = polyLine.ControlPointLocations;
I assumed that if you calculate a triangle's area, you are passing a `Polyline` composed of 4 points.
We may not need this overload method.

2023-01-06 02:11 UTC, cesarecaoduro commented on src/GShark/Core/Trigonometry.cs
> +            var pts = polyLine.ControlPointLocations;
I think is still valid to keep it, as long as we introduce a check on the number of control points, and that first and last point are coincident (or polyline is closed)

2023-01-06 08:25 UTC, d3ssy commented on src/GShark/Core/Trigonometry.cs
> +            var pts = polyLine.ControlPointLocations;
This method should be more specific given the name. It  should take 3 points as parameters only. Using the vector based method for the area it shouldn't require any collinearity or coplanarity checks.

2023-01-06 08:31 UTC, d3ssy requested changes

2023-01-06 08:31 UTC, d3ssy commented on src/GShark/Core/Trigonometry.cs
> +        ///     Gets the orientation between tree points in the plane.<br />
three

2023-01-06 08:31 UTC, d3ssy commented on src/GShark/Core/Trigonometry.cs
> +        ///     Determines if the provide points are on the same plane within specified tolerance.
....if the given points lie on the same plane within the specified tolerance.

2023-01-06 08:31 UTC, d3ssy commented on src/GShark/Core/Trigonometry.cs
> +        ///     The segment is deconstruct in two points and two t values.
This doc summary is hard to understand!

2023-01-06 08:31 UTC, d3ssy commented on src/GShark/Core/Trigonometry.cs
> +        public static double AreaOfTriangle(PolyLine polyLine)
Suggest to remove this as we have no test for to check that a polyline is in fact a triangle.

2023-01-06 08:31 UTC, d3ssy commented on src/GShark/Core/Trigonometry.cs
> +        public static double AreaOfTriangle(Point3 pt1, Point3 pt2, Point3 pt3)
If you use the vector based method instead distance method (same as Alan has in area calc in mesh face) you can avoid any checks on two vertices sharing same location.

2023-01-06 22:00 UTC, sonomirco commented on src/GShark/Core/Trigonometry.cs
> +            var pts = polyLine.ControlPointLocations;
I'll remove this overload for now.

2023-01-06 22:08 UTC, sonomirco commented on src/GShark/Core/Trigonometry.cs
> +        public static double AreaOfTriangle(Point3 pt1, Point3 pt2, Point3 pt3)
So are you saying to have two vectors as inputs or keep 3 points and calculate the vector between the points?
In both cases, if the vector is zero or the distance is zero, the area will return zero, so the check is unnecessary.

2023-01-11 08:40 UTC, d3ssy commented on src/GShark/Core/Trigonometry.cs
> +        public static double AreaOfTriangle(Point3 pt1, Point3 pt2, Point3 pt3)
3 pts as input (then it's definitely a triangle). Use Vectors.

2023-01-28 03:46 UTC, sonomirco commented
@d3ssy @cesarecaoduro ready to be merged.

2023-01-29 23:25 UTC, cesarecaoduro approved these changes

2023-02-04 02:21 UTC, merged