Add method AsVector for Point3
GSharker/G-Shark pull request #403
Opened 2023-01-20 03:13 UTC by chuongmep

### What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

### Description

this allow a point3 quicky convert to vector or vector3

### Related Tickets & Documents

### Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📓 docs
- [ ] 🙅 no documentation needed

2023-01-28 03:09 UTC, sonomirco requested changes
@chuongmep  When you open a PR could you please:

- add the label
- select a reviewer
- write compensable information about what the PR is trying to solve.
Thanks

2023-01-28 03:09 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/Point3Tests.cs
> +        public void TestConvertAsVector(double x,double y,double z)
Could you please follow the same conventions we use for the unit test? Thanks.
Naming Convention and the AAA pattern (Arrange, Act and Assert)

2023-01-28 03:09 UTC, sonomirco commented on src/GShark/Geometry/Point3.cs
> +        /// Get the Vector with the same X, Y, and Z component
Gets the vector with the same X, Y, and Z component.

2023-01-28 03:09 UTC, sonomirco commented on src/GShark/Geometry/Point3.cs
> +        }
Why do we need this?

2023-01-28 03:47 UTC, chuongmep commented on src/GShark/Geometry/Point3.cs
> +        }
In process, we need quick convert point to vector for move, transform, check direction point, some thing like that.

2023-02-04 02:34 UTC, sonomirco approved these changes

2023-02-04 02:34 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/Point3Tests.cs
> +                .Be(3);
Could you please group the 3A.
Thanks.

2023-02-04 02:34 UTC, sonomirco commented on src/GShark/Geometry/Point3.cs
> +        /// <returns></returns>
Returns?

2023-02-04 02:34 UTC, sonomirco commented on src/GShark/Geometry/Point3.cs
> +        /// <returns></returns>
Returns?

2023-02-06 00:07 UTC, chuongmep commented on src/GShark.Test.XUnit/Geometry/Point3Tests.cs
> +                .Be(3);
Hi @sonomirco , can help me explain detail about 3A you want group ? Because I grouped it with XYZ components for function.

2023-02-07 13:41 UTC, d3ssy reviewed
We implemented `implicit operator` on [Point3](https://github.com/GSharker/G-Shark/blob/38fa71781bde9f3a5b60c3310d93540e810e7af8/src/GShark/Geometry/Point3.cs#L243) and [Vector3](https://github.com/GSharker/G-Shark/blob/ebb2a46961c457cf9d0029704d1aebdcfde77d6b/src/GShark/Geometry/Vector3.cs#L183) to handle implicit conversion between the two so you don't ever need to explicitly convert from one to the other. 

Unless I'm missing something else we can kill this PR. Was there an open issue that prompted this feature?

2023-02-07 20:09 UTC, sonomirco commented
Agree

2023-02-08 00:34 UTC, chuongmep commented
I agreee for that.

2023-02-08 00:34 UTC, closed without merging