Add TripleProduct Method
GSharker/G-Shark pull request #404
Opened 2023-01-20 04:18 UTC by chuongmep

### What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

### Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

### Related Tickets & Documents

### Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📓 docs
- [ ] 🙅 no documentation needed

2023-01-28 03:06 UTC, sonomirco requested changes

2023-01-28 04:00 UTC, chuongmep commented on src/GShark.Test.XUnit/Geometry/Vector3Tests.cs
> +        public void TestReturnResultOfTripleProduct()
Resolved, thank you, will be follow with conventions for next time.

2023-02-04 02:31 UTC, sonomirco approved these changes

2023-02-04 02:31 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/Vector3Tests.cs
> +            result2.Should().Be(-527);
Or you use a `Theory` passing multiple parameters, or you groups the `3A`

2023-02-06 00:10 UTC, chuongmep commented on src/GShark.Test.XUnit/Geometry/Vector3Tests.cs
> +            result2.Should().Be(-527);
Hi @sonomirco , can help me explain detail about 3A you want group ? Because I grouped it with XYZ components for function.

2023-02-07 13:31 UTC, d3ssy commented on src/GShark.Test.XUnit/Geometry/Vector3Tests.cs
> +            result2.Should().Be(-527);
Hi @chuongmep! We're just super anal about consistency 🤣.

2023-02-07 13:32 UTC, d3ssy commented on src/GShark.Test.XUnit/Geometry/Vector3Tests.cs
> +            result2.Should().Be(-527);
I would also rename the test to `It_Returns_Result_Of_Triple_Product()`.

2023-02-08 00:39 UTC, chuongmep commented on src/GShark.Test.XUnit/Geometry/Vector3Tests.cs
> +            result2.Should().Be(-527);
Thank you @d3ssy @sonomirco , it is updated now.

2023-02-09 10:34 UTC, d3ssy approved these changes

2023-02-09 10:35 UTC, merged