Add Get Centroid method
GSharker/G-Shark pull request #405
Opened 2023-01-20 05:43 UTC by chuongmep

### What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

### Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

### Related Tickets & Documents

### Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📓 docs
- [ ] 🙅 no documentation needed

2023-01-28 03:04 UTC, sonomirco requested changes

2023-01-28 03:04 UTC, sonomirco commented on src/GShark/Geometry/Point3.cs
> +        public static Point3 Centroid(params Point3[] points)
Could we have only one method which takes `IEnumerable<Point3>` or `IList<Point3>` as input?

2023-01-28 03:04 UTC, sonomirco commented on src/GShark/Geometry/Point3.cs
> +        /// Returns the centroid of an arbitrary collection of points
The point at the end of the sentence.

2023-01-28 03:04 UTC, sonomirco commented on src/GShark/Geometry/Point3.cs
> +        /// <param name="points">a list of points</param>
A collection of points.

2023-01-28 03:04 UTC, sonomirco commented on src/GShark/Geometry/Point3.cs
> +        /// Returns the centroid of an arbitrary collection of points
Calculate the centroid of....

2023-01-28 03:04 UTC, sonomirco commented on src/GShark.Test.XUnit/Geometry/Point3Tests.cs
> +        public void TestReturnCentroid()
Could you please follow the same conventions we use for the unit test? Thanks.
Naming Convention and the AAA pattern (Arrange, Act and Assert)

2023-01-28 03:55 UTC, chuongmep commented on src/GShark/Geometry/Point3.cs
> +        public static Point3 Centroid(params Point3[] points)
will be change this, thank you.

2023-01-28 03:59 UTC, chuongmep commented on src/GShark/Geometry/Point3.cs
> +        /// Returns the centroid of an arbitrary collection of points
this mothod removed and merge with method input is IEnumerable

2023-02-04 02:25 UTC, sonomirco approved these changes

2023-02-06 22:48 UTC, merged